// api/_cloudinary.js
//
// โค้ดกลางสำหรับดึงรูปทั้งโฟลเดอร์จาก Cloudinary (ใช้ร่วมกันหลาย endpoint เช่น
// /api/gallery, /api/about-images) ไฟล์นี้ขึ้นต้นด้วย "_" ตามธรรมเนียมของ Vercel
// แปลว่าจะไม่ถูกสร้างเป็น route ของตัวเอง เป็นแค่ไฟล์ช่วยเหลือ (shared lib) เท่านั้น

const MAX_TOTAL_IMAGES = 1000; // เพดานสูงสุดที่จะดึง กันโฟลเดอร์ใหญ่ผิดปกติทำให้หน้าเว็บช้า
const PAGE_SIZE = 200; // Cloudinary Search API อนุญาตสูงสุด 500 ต่อ 1 คำขอ ใช้ 200 เพื่อความเสถียร
const MAX_PAGES = Math.ceil(MAX_TOTAL_IMAGES / PAGE_SIZE);

// รูปแบบไฟล์ที่โชว์เป็น <img> ได้จริงบนเว็บทั่วไป (กันไฟล์แปลก ๆ เช่น .psd, .ai ที่ Cloudinary
// จัดเป็น resource_type: image เหมือนกันแต่เบราว์เซอร์เปิดไม่ได้)
const DISPLAYABLE_FORMATS = new Set(["jpg", "jpeg", "png", "webp", "gif", "avif", "svg", "heic"]);

// แทรก transformation string เข้าไปใน secure_url เพื่อขอรูปย่อจาก Cloudinary
function buildThumbUrl(secureUrl, transform) {
  if (!secureUrl) return secureUrl;
  return secureUrl.replace("/upload/", `/upload/${transform}/`);
}

function deriveTitle(publicId) {
  const raw = (publicId.split("/").pop() || "").replace(/[-_]/g, " ").replace(/\s+/g, " ").trim();
  // ชื่อไฟล์อัตโนมัติจากกล้อง/มือถือ เช่น "IMG 20250612 143210" หรือตัวเลขล้วน ๆ -> ไม่มีความหมาย ปล่อยว่าง
  const looksAutoGenerated = /^(img|dsc|photo)?\s*\d{6,}\s*\d*$/i.test(raw) || /^\d+$/.test(raw);
  return looksAutoGenerated ? "" : raw;
}

async function fetchPage({ cloudName, auth, expression, cursor }) {
  const body = {
    expression,
    sort_by: [{ created_at: "desc" }],
    max_results: PAGE_SIZE,
    resource_type: "image", // กันไฟล์ที่ไม่ใช่รูป (วิดีโอ/pdf/raw) ไม่ให้หลุดเข้ามา
  };
  if (cursor) body.next_cursor = cursor;

  const res = await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/resources/search`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Basic ${auth}`,
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Cloudinary error (${res.status}): ${errText}`);
  }
  return res.json();
}

// ดึงรูปทั้งหมดในโฟลเดอร์ที่กำหนด (รวมโฟลเดอร์ย่อย) พร้อมกรอง/แปลงข้อมูลให้พร้อมใช้งาน
// thumbTransform: transformation string สำหรับรูปย่อ (ปรับขนาดตามจุดใช้งาน เช่น grid vs slider)
export async function fetchCloudinaryFolder({ folder, thumbTransform = "w_500,h_500,c_fill,f_auto,q_auto" }) {
  const { CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = process.env;

  if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_API_KEY || !CLOUDINARY_API_SECRET) {
    const err = new Error(
      "ยังไม่ได้ตั้งค่า Cloudinary environment variables (CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET)"
    );
    err.statusCode = 500;
    throw err;
  }

  const auth = Buffer.from(`${CLOUDINARY_API_KEY}:${CLOUDINARY_API_SECRET}`).toString("base64");
  // ครอบคลุมทั้งรูปที่อยู่ตรงในโฟลเดอร์ และรูปในโฟลเดอร์ย่อย
  const expression = `asset_folder="${folder}"`;
  
  let resources = [];
  let cursor;
  let page = 0;

  do {
    const data = await fetchPage({ cloudName: CLOUDINARY_CLOUD_NAME, auth, expression, cursor });
    resources = resources.concat(data.resources || []);
    cursor = data.next_cursor;
    page += 1;
  } while (cursor && page < MAX_PAGES && resources.length < MAX_TOTAL_IMAGES);

  return resources
    .filter((r) => DISPLAYABLE_FORMATS.has((r.format || "").toLowerCase()))
    .slice(0, MAX_TOTAL_IMAGES)
    .map((r) => ({
      id: r.asset_id || r.public_id,
      publicId: r.public_id,
      url: r.secure_url,
      thumbUrl: buildThumbUrl(r.secure_url, thumbTransform),
      width: r.width,
      height: r.height,
      createdAt: r.created_at,
      title: deriveTitle(r.public_id),
    }));
}
